# Generated by Django 3.1.7 on 2021-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], max_length=50)),
                ('skintone', models.CharField(choices=[('1', 'Fair'), ('2', 'Olive'), ('3', 'Brown'), ('4', 'Black')], max_length=50)),
                ('height', models.CharField(max_length=75)),
                ('weight', models.CharField(max_length=75)),
                ('haircolors', models.CharField(choices=[('black', 'black'), ('brown', 'brown'), ('Blond', 'Blonde'), ('Red', 'Red'), ('White/Gray', 'White/Gray')], max_length=50)),
                ('mobno', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], max_length=50)),
                ('mobno', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('feed', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='user_image')),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
