# Generated by Django 3.1.7 on 2021-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custinfo',
            options={'verbose_name_plural': "Customer's Information"},
        ),
        migrations.AlterModelOptions(
            name='employeeinfo',
            options={'verbose_name_plural': "Employee's Information"},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback by Users'},
        ),
        migrations.AlterModelOptions(
            name='trends',
            options={'verbose_name_plural': 'Manage Trends'},
        ),
    ]
