# Generated by Django 3.1.7 on 2021-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custinfo',
            options={'verbose_name_plural': "Customer's Information"},
        ),
        migrations.AlterModelOptions(
            name='employeeinfo',
            options={'verbose_name_plural': "Employee's Information"},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback by Users'},
        ),
        migrations.AlterModelOptions(
            name='trends',
            options={'verbose_name_plural': 'Manage Trends'},
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='user',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='skintone',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Olive', 'Olive'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50),
        ),
    ]
