# Generated by Django 3.1.7 on 2021-03-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0002_auto_20210313_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='user',
            new_name='id',
        ),
    ]
