# Generated by Django 3.1.7 on 2021-03-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0003_auto_20210316_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
