# Generated by Django 2.2.7 on 2021-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0004_auto_20210316_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='custinfo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
