# Generated by Django 2.2.7 on 2021-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0006_auto_20210424_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='mobno',
            field=models.IntegerField(blank=True),
        ),
    ]
