# Generated by Django 2.2.7 on 2021-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0008_auto_20210424_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='mobno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
