# Generated by Django 2.2.7 on 2021-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kowiapp', '0009_auto_20210424_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='mobno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
